# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson_21' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Lesson_21

  target 'Lesson_21Tests' do
    inherit! :search_paths
    # Pods for testing
  end


  target 'Lesson_21UITests' do
    inherit! :search_paths
    # Pods for testing

pod 'AFNetworking', '~> 3.0'

  end

end
